disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "tech-bro的技術筆記"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "Subject.png"

["params.author"]
name = "tech-bro"
